### PR TITLE
Very minor additions

### PR DESCRIPTION
**Pull request by RyDroid**

### CODE REVIEW

**Comment by aidin36** [comment]
Thanks! That's very good.

I think ``.editorconfig`` shouldn't appear here. That's a configuraion for a specific editor, right? Everyone prefare to use a specific editor, if we keep their configurations here, there would be a lot of config files here! More than that, each person have their own preferences.

Please remove the ``.editorconfig`` file, and I'll merge your request.

**Comment by RyDroid** [comment]
http://editorconfig.org/
> EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs.

So it absolutely not a configuraion for a specific editor.

**Comment by aidin36** [comment]
Oh! Didn't know that! Sorry.
I searched the web to see what's an ``.editorconfig`` file is, but I didn't see the site you just mentioned.
Thanks for teaching me that (:

**Comment by RyDroid** [comment]
Not a problem. :)

**Pull request merged**
