### PR TITLE
Adding french translation

### PR DESCRIPTION
**Pull request by RyDroid**

### CODE REVIEW

**Comment by aidin36** [comment]
That's great!

I think the copyright notice should be the same as other files: *Copyright (c) 2015, Aidin Gharibnavaz*. The copyright law says so. As far as I know, the whole application should have one copyright holder, which can be a single person or a group.

To keep your credit, I recommend adding these lines under the licence notice:

```
Created on: 2015/12/24
Author: Nicola Spanti (RyDroid) <dev@nicola-spanti.info>
```

Also, the name of the application should be appear instead of *This program*. The easiest way is to copy-paste the notice from other source files.

Thanks for the great job.

**Comment by RyDroid** [comment]
Where did you read that an app MUST have only 1 copyright holder? As much as I know, it can be useful (for relicensing or [enforce the license](https://www.gnu.org/licenses/why-assign.html)), but it is not an obligation.

**Comment by aidin36** [comment]
You're right, copyright law doesn't force one copyright holder. What I tried to explain, was what you said: Multiple copyright holders make it hard to enforce a license.

Seems that you already know the benefits of having one copyright holder. The question is, what benefits will we gain by having multiple copyright holders?

**Comment by aidin36** [comment]
I should make it clear that I'm just trying to do the best possible thing (-: I maybe wrong at this.

**Comment by RyDroid** [comment]
I edited the copyright notice.

**Comment by aidin36** [comment]
Thanks (:

**Pull request merged**
